TokyoTech_Stamprally_Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('accounts/',include('accounts.urls')),
]

accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from  . import views
from django.urls import path
from django.views.generic import CreateView

app_name='accounts'

urlpatterns = [
    path('login/', views.Login.as_view(),name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    
    #path('demo/', views.Demo.as_view(), name="demo"),
    path('profile_create/', views.ProfileCreate.as_view(), name='profile_create'),
    #path('profile_setting/<int:pk>/', views.ProfileSetting.as_view(), name='profile_setting'),

]

base/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from  . import views
from django.urls import path
from django.views.generic import CreateView

app_name='base'

urlpatterns = [
    path('',views.IndexView.as_view(), name="index"),
    path('home/', views.Home.as_view(), name='home'),
]

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.db.models.deletion import CASCADE
from django.db.models.fields import related
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class CustomUserManager(UserManager):
    """ユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True,)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email



class Unit(models.Model):
    unit = models.IntegerField(null=True)

    def __str__(self):
        return 'U{u}'.format(u=self.unit)

    class Meta: 
        ordering = ['unit']



class Profile(models.Model):
    user=models.OneToOneField(User, verbose_name='ユーザー',on_delete=CASCADE)

    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, default = 25) #harsh
    
    profile_picture=models.ImageField(verbose_name='プロフィール写真', blank=True, null=True)
    nickname=models.TextField(verbose_name='ニックネーム', max_length=20)
    comment=models.TextField(verbose_name='ひとことコメント', max_length=50,null=True)

    CHOICES = (
        ('a', '学院はどこですか？'),
        ('b', '部活サークルは？'),
        ('c', '出身県は？'),
        ('d', '出身高校は？'),
        ('e', '興味のある分野は？'),
        ('f', '将来の夢はなんですか？'),
    )
    question1 = models.CharField(max_length=150, choices = CHOICES)
    question2 = models.CharField(max_length=150, choices = CHOICES)
    answer1 = models.CharField(max_length=150, null=True, blank=True, default=None)
    answer2 = models.CharField(max_length=150, null=True, blank=True, default=None)

    #harsh
    points = models.IntegerField(default = 0)  
    key = models.CharField(max_length=10, null=True, blank=True)
    key_vector = models.CharField(max_length=200, null=True, default='0')

    def __str__(self):
        return self.nickname


    class Meta:
        verbose_name_plural='Profile'

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.forms import fields
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm
)

UserModel = get_user_model()

#ログイン用フォーム
class EmailAuthenticationForm(forms.Form):
    email = forms.EmailField(max_length=254,
                             widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(label=_("Password"), strip=False,
                               widget=forms.PasswordInput)
    error_messages = {
        'invalid_login': "Eメールアドレス または パスワードに誤りがあります。",
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the label for the "email" field.
        self.email_field = UserModel._meta.get_field("email")
        if self.fields['email'].label is None:
            self.fields['email'].label = capfirst(self.email_field.verbose_name)
    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        email_len=len(email)
        m_address=email[email_len-14:]

        #mアドレス認証
        if not m_address=="m.titech.ac.jp":
            raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'email': self.email_field.verbose_name})

        


        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'email': self.email_field.verbose_name})
            else:
                self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(self.error_messages['inactive'], code='inactive')
    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None
    def get_user(self):
        return self.user_cache

#ログイン用フォームver.2


User = get_user_model()


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()

        #mアドレス認証
        email_len=len(email)
        m_address=email[email_len-14:]
        if not m_address=="m.titech.ac.jp":
            raise forms.ValidationError('mアドレスを使ってください！')
        
        return email

from accounts.models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        SELECTION1=(('a','学院はどこですか？'),('b','部活・サークルは？'),('c','出身県はどこですか？'),('d','出身高校はどこですか？'),('e','興味のある分野はなんですか？'),('f','将来の夢はなんですか？'))
        fields=('unit','profile_picture','nickname','comment','question1','question2','answer1','answer2',)

accounts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.checks import messages
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.views import generic
from django.views.generic.base import TemplateView
from .forms import LoginForm, UserCreateForm
from django.contrib.auth import login


User=get_user_model()
    

class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def get_success_url(self):
        return '/home/'


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'accounts/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('accounts/mail_template/create/subject.txt', context)
        message = render_to_string('accounts/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('accounts:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録完了"""
    template_name = 'accounts/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'accounts/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                    return super().get(request, **kwargs)


from accounts.forms import ProfileForm
from .models import Profile
from django.urls import reverse_lazy

class ProfileCreate(LoginRequiredMixin, generic.CreateView):
    template_name='accounts/profile_create.html'
    model=Profile
    form_class=ProfileForm
    success_url=reverse_lazy('base:home')

    def form_valid(self, form):
        profile=form.save(commit=False)
        profile.user=self.request.user
        profile.save()
        return super().form_valid(form)


class Demo(TemplateView):
    template_name="accounts/user_create_complete.html"


class ProfileSetting(LoginRequiredMixin,generic.DetailView):
    model=Profile
    template_name='accounts/profile_setting.html'
    

templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block title %}TokyoTech_StamprallyProject | login {% endblock %}

{% block head %}
<link href="{% static 'css/login_style.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<section class="hero">
    <h1>WELCOME</h1>

    {% if user.is_authenticated %}
    <p>ログインは完了しています</p>
    <a class="btn btn-primary btn-lg" href="{% url 'base:home' %}">ホーム</a>
    <p></p>
    <a class="btn btn-primary btn-lg" href="{% url 'accounts:logout' %}">ログアウト</a>

    {% else %}
    <form method="post" class="form">
        {% csrf_token %}
        <input type="hidden" name="text" value="{{ next }}">
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">ログイン</button>
    </form>

    <a href="{% url 'accounts:user_create' %}"><p class="p">アカウントを作成</p></a>

    
    {% endif %}
</section>

    
  

{% endblock %}

templates/accounts/profile_create.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block title %}TokyoTech_StamprallyProject | profile create{% endblock %}

{% block head %}
<link href="{% static 'css/profile_create_style.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<section class="hero">
    <h1>プロフィール設定</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="text" value="{{ next }}">
           {% bootstrap_form form %}
           <button type="submit" class="btn btn-primary">完了</button>
       </form>
</section>
{% endblock %}

templates/accounts/profile_setting.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block title %}TokyoTech_StamprallyProject | profile setting{% endblock %}

{% block head %}
<link href="{% static 'css/profile_setting_style.css' %}" rel="stylesheet">
{% endblock %}

{% bloch contents %}

{% endblock %}

templates/accounts/user_create.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block title %}TokyoTech_StamprallyProject |signup{% endblock %}

{% block head %}
<link href="{% static 'css/user_create_style.css' %}" rel="stylesheet">
{% endblock %}


{% block contents %}
<section class="hero">
    <h1>Sign Up</h1>
    <p>メールアドレスはmアドレスを使ってください！</p>
    <form method="POST">
     {% csrf_token %}
     <input type="hidden" name="text" value="{{ next }}">
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
    <a href="{% url 'accounts:login' %}"><p>ログイン</p></a>
</section>
{% endblock %}

templates/accounts/user_create_complete.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block title %}TokyoTech_StamprallyProject |signup complete{% endblock %}

{% block head %}
<link href="{% static 'css/user_create_complete_style.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<section class="hero">
    <h1>Sign Up</h1>
    <h1>Completed!</h1>
    <p class="message">
        本登録が完了しました。<br>
        プロフィール設定に進んでください<br>
    </p>
    
    <a class="btn btn-primary btn-lg" href="{% url 'accounts:profile_create' %}">プロフィール設定</a>
    
</section>
{% endblock %}

templates/accounts/user_create_done.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block title %}TokyoTech_StamprallyProject |signup done{% endblock %}

{% block head %}
<link href="{% static 'css/user_create_done_style.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<section class="hero">
    <h1 class="signup">Sign Up</h1>
    <h1>Done</h1>

    <p class="message">会員登録確認メールを送信しました。<br>
        まだ、会員登録は完了していません。<br>
        確認メールを送信しましたので、<br>
        確認メールに記載されているリンクから<br>
        本登録を行ってください。</p>
   
</section>
{% endblock %}